- debug:
   var: user_groups
- name: Ensure groups are present or absent
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:  "{{ user_groups }}"

# - name: Ensure users are present or absent
#   ansible.builtin.user:
#     name: "{{ item.name }}"
#     shell: "{{ item.shell }}"
#     state: "{{ item.state }}"
#     ssh_key: "{{ item.ssh_key }}"
#     password: "{{ item.password }}"
#     groups: "{{ item.groups | join(',') }}"
#     append: yes
#   loop: "{{ users }}"
#   when: users is defined and users | length > 0