- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: item.shell == '/bin/zsh'
  loop: "{{ users }}"
